version: '2'
services:
  chat-bot:
    image: 'valentinvieriu/booksclub:chatbot-1.0.1'
    build: .
    restart: always
    environment: 
      MQTT_SERVER: 'mqtt.iplatform.ro'
networks:
  default:
    external:
      name: infra_default