version: '2'
services:
  chat-bot:
    # image: '${REGISTRY_BASE_URL}/booksclub/chatbot:1.0.0'
    image: 'valentinvieriu/booksclub:chatbot-1.0.0'
    build: .
    restart: always
    environment: 
      MQTT_SERVER: 'mqtt.iplatform.ro'
networks:
  default:
    external:
      name: infra_default